
ARG VARIANT="buster"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

RUN apt update && \
    apt install -y texlive-base make texlive-binaries latexmk texlive-lang-italian texlive-latex-recommended texlive-latex-extra